### ISSUE TITLE
Destroys backend when in repeater

### ISSUE THREAD

**Issue by enthus1ast** [ca-team-sulley/bolt-extension-html5-audio#5]
> Bolt 3.6.9

```
        audioupload:
            group: audio
            type: repeater
            fields:
                label:
                    type: text
                file:
                    type: audio
                    upload: events    
```

![2019-08-12 14_03_14-Window](https://user-images.githubusercontent.com/13794470/62863750-0607ae00-bd0a-11e9-8fbc-4ed7cdb51298.png)
